name: Auto Comment on New Issue
on:
  issues:
    types: [opened]

jobs:
  reply-to-issue:
    runs-on: ubuntu-latest
    permissions:
      issues: write  # Issueã«æ›¸ãè¾¼ã‚€æ¨©é™ã‚’è¨±å¯
    steps:
      - name: Post a comment
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thank you for creating an issue! Please wait a moment as we will get back to you after reviewing the issue.ğŸ™"
            })
